const materias = [
  "Anatomía", 
  "Histología", 
  "Bioquímica", 
  "Biofísica", 
  "Fisiología", 
  "Microbiología", 
  "Parasitología", 
  "Farmacología", 
  "Patología", 
  "Inmunología", 
  "Psicología Médica", 
  "Genética", 
  "Embriología", 
  "Semiología", 
  "Clínica Médica", 
  "Clínica Quirúrgica", 
  "Ginecología", 
  "Pediatría", 
  "Salud Pública", 
  "Psiquiatría", 
  "Neurología", 
  "Oftalmología", 
  "Otorrinolaringología", 
  "Ortopedia", 
  "Emergencias", 
  "Ética Médica", 
  "Investigación", 
  "Tesis"
];
